version: 0.2

phases:
  install:
    commands:
      - echo "Installing NGINX"
      - sudo apt-get update -y
      - sudo apt-get install nginx -y

  build:
    commands:
      - echo "Copying index.html to NGINX root"
      - sudo cp index.html /usr/share/nginx/html/

artifacts:
  files:
    - '**/*'
