version: 0.2 
phases: 
  install: 
    commands: 
      - apt-get update -y && apt-get install nginx -y 
  build:
    commands:
      - cp index.html /var/www/html/
      
artifacts: 
  files: 
      - '**/*'
